import { useState } from 'react'
import { ArrowLeft, ArrowRight, ChevronDown, RotateCcw, Upload } from 'lucide-react'
import { analysisFiles, example, importGitHub, importZip, makeTopics, type Project, type SourceFile } from './project'
import { quickQuestions, tour, type Citation, type Lesson, type Question } from './learning'

type Screen = 'welcome' | 'role' | 'tour' | 'check' | 'review' | 'library'
type Answer = { question: Question; choice: number }
const message = (error: unknown) => error instanceof Error ? error.message : 'That did not work. Try again.'
const topicCitation = (file: SourceFile, index: number): Citation => {
  const patterns = [/"(?:react|vite|typescript|build)"/, /createRoot|\.render\(|import\s+App/, /return\s*\(|=>\s*\(/, /createBrowserRouter|<Route|RouterProvider|routes\s*=/, /useState|useReducer|useContext/, /\bfetch\(|\baxios\.|supabase\.from/, /font-family|display:|margin:/, /"build"|deploy|outputDirectory/]
  const line = file.content.split('\n').findIndex(text => patterns[index].test(text)) + 1
  return { path: file.path, line: line || 1 }
}
async function ask<T>(project: Project, action: 'lesson' | 'quiz', index: number): Promise<T> {
  const response = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, index, role: 'frontend', files: analysisFiles(project, index, action) }) })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'The extra explanation is unavailable.')
  return data as T
}
function Evidence({ citation, project }: { citation: Citation; project: Project }) {
  const [open, setOpen] = useState(false)
  const lines = project.files.find(file => file.path === citation.path)?.content.split('\n') ?? []
  const start = Math.max(0, citation.line - 3)
  return <div className="evidence"><button onClick={() => setOpen(!open)} aria-expanded={open}>See the code: {citation.path}:{citation.line} <ChevronDown size={15}/></button>{open && <pre>{lines.slice(start, citation.line + 3).map((line, index) => <span className={start + index + 1 === citation.line ? 'target-line' : ''} key={index}><b>{start + index + 1}</b>{line || ' '}{'\n'}</span>)}</pre>}</div>
}
export default function App() {
  const [screen, setScreen] = useState<Screen>('welcome')
  const [source, setSource] = useState<'github' | 'zip'>('github')
  const [url, setUrl] = useState('')
  const [project, setProject] = useState<Project | null>(null)
  const [consent, setConsent] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [stop, setStop] = useState(0)
  const [deep, setDeep] = useState<Record<number, Lesson>>({})
  const [deepBusy, setDeepBusy] = useState(false)
  const [deepError, setDeepError] = useState('')
  const [answers, setAnswers] = useState<Answer[]>([])
  const [choice, setChoice] = useState<number | null>(null)
  const [questionIndex, setQuestionIndex] = useState(0)
  const [advanced, setAdvanced] = useState(false)
  const [advancedQuestions, setAdvancedQuestions] = useState<Question[]>([])
  const [advancedBusy, setAdvancedBusy] = useState(false)
  const [advancedError, setAdvancedError] = useState('')
  const [chapter, setChapter] = useState(0)
  const [chapterLessons, setChapterLessons] = useState<Record<number, Lesson>>({})
  const [chapterBusy, setChapterBusy] = useState(false)
  const [chapterError, setChapterError] = useState('')
  const steps = project ? tour(project) : []
  const chapters = project ? makeTopics(project) : []
  const quiz = project ? (advanced ? advancedQuestions : quickQuestions(project)) : []
  const current = quiz[questionIndex]
  function begin(value: Project) { setProject(value); setConsent(false); setDeep({}); setChapterLessons({}); setAnswers([]); setStop(0); setError(''); setScreen('role') }
  function reset() { setScreen('welcome'); setProject(null); setError(''); setAnswers([]); setAdvanced(false); setAdvancedQuestions([]); setQuestionIndex(0) }
  async function loadUrl() { setBusy(true); setError(''); try { begin(await importGitHub(url)) } catch (err) { setError(message(err)) } finally { setBusy(false) } }
  async function loadZip(file?: File) { if (!file) return; setBusy(true); setError(''); try { begin(await importZip(file)) } catch (err) { setError(message(err)) } finally { setBusy(false) } }
  async function loadDeep() { if (!project || !consent) return; setDeepBusy(true); setDeepError(''); try { const lesson = await ask<Lesson>(project, 'lesson', [0, 1, 4, 7][stop]); setDeep(old => ({ ...old, [stop]: lesson })) } catch (err) { setDeepError(message(err)) } finally { setDeepBusy(false) } }
  function startQuick() { setAnswers([]); setAdvanced(false); setAdvancedQuestions([]); setQuestionIndex(0); setChoice(null); setScreen('check') }
  function submitAnswer() { if (!current || choice === null) return; setAnswers(old => [...old, { question: current, choice }]); setChoice(null); if (questionIndex + 1 < quiz.length) setQuestionIndex(index => index + 1); else setScreen('review') }
  async function loadAdvanced(section: number) { if (!project || !consent) return; setAdvancedBusy(true); setAdvancedError(''); setAdvancedQuestions([]); setQuestionIndex(0); setChoice(null); try { const data = await ask<{ questions: Question[] }>(project, 'quiz', section); setAdvancedQuestions(data.questions); setAdvanced(true); setAnswers([]); setScreen('check') } catch (err) { setAdvancedError(message(err)) } finally { setAdvancedBusy(false) } }
  async function loadChapter(index: number) { if (!project || !consent) return; setChapterBusy(true); setChapterError(''); try { const value = await ask<Lesson>(project, 'lesson', index); setChapterLessons(old => ({ ...old, [index]: value })) } catch (err) { setChapterError(message(err)) } finally { setChapterBusy(false) } }
  return <div className="app"><header className="top"><button className="brand" onClick={reset} aria-label="Recode home"><span>r.</span><b>recode</b></button><span className="top-note">Understand the code you ship.</span><span className="top-side">A project reading tool</span></header><main className="main">
    {screen === 'welcome' && <div className="welcome"><div className="welcome-copy"><span className="eyebrow">RECODE 2026</span><h1>You built it. <em>Now own the explanation.</em></h1><p>Bring a small React project. In a few minutes, you will know what starts the app, what changes on screen, and how to talk through it. Then prove it to yourself with five questions.</p><button className="primary" onClick={() => begin(example)}>Try the guided project <ArrowRight size={17}/></button><p className="under-button">No account. No setup. Use an example before sharing your own code.</p></div><div className="preview" aria-label="How Recode works"><div className="preview-top"><span>THE MOMENT</span><strong>“So, how does your app work?”</strong></div><div className="preview-lines"><span>01</span><p>Find where the app starts.</p><span>02</span><p>Trace one thing a user can do.</p><span>03</span><p>Say it in your own words.</p></div><div className="preview-end">You can point to the file behind each answer.</div></div><section className="import"><div><span className="eyebrow">YOUR CODE</span><h2>Ready to use your project?</h2><p>Public GitHub repo or a ZIP from your device.</p></div><div className="switch" role="tablist"><button role="tab" aria-selected={source === 'github'} onClick={() => setSource('github')}>GitHub</button><button role="tab" aria-selected={source === 'zip'} onClick={() => setSource('zip')}>ZIP file</button></div>{source === 'github' ? <div className="import-entry"><label htmlFor="repo">Public repository link</label><div className="url-row"><input id="repo" type="url" placeholder="https://github.com/owner/repo" value={url} onChange={event => setUrl(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && url.trim() && !busy) void loadUrl() }}/><button className="secondary" disabled={busy || !url.trim()} onClick={loadUrl}>{busy ? 'Reading files…' : 'Use this repo'} <ArrowRight size={16}/></button></div><small>Open the public repo on GitHub and copy its address. Recode does not need your GitHub login.</small></div> : <div className="import-entry"><label className="file-drop"><Upload size={18}/><strong>{busy ? 'Opening your ZIP…' : 'Choose a ZIP file'}</strong><input type="file" accept=".zip,application/zip" disabled={busy} onChange={event => void loadZip(event.target.files?.[0])}/></label><details><summary>How do I get a ZIP from GitHub?</summary><p>Open your repo, tap <b>Code</b>, then <b>Download ZIP</b>. Select that downloaded file here. Keep it zipped.</p></details></div>}{error && <p className="error" role="alert">{error}</p>}<p className="privacy">Recode reads selected text files. Do not import secrets or confidential code. AI receives selected excerpts only after you opt in.</p></section></div>}
    {screen === 'role' && project && <div className="narrow"><button className="back" onClick={reset}><ArrowLeft size={16}/> Change project</button><span className="eyebrow">YOUR PROJECT</span><h1>Start with the part you touched.</h1><p className="lead">You do not need to know everything first. We will follow the code from a screen you can see to the files behind it.</p><div className="project-line"><strong>{project.name}</strong><span>{project.files.length} readable files · {project.source}</span></div><div className="role"><span>AVAILABLE PATH</span><h2>Frontend developer</h2><p>Learn what starts the page, which code responds to clicks, how it is styled, and what the source can and cannot tell us about hosting.</p><small>Choosing this path does not claim you wrote every file.</small></div><button className="primary" onClick={() => setScreen('tour')}>Show me my project <ArrowRight size={17}/></button><label className="ai-consent"><input type="checkbox" checked={consent} onChange={event => setConsent(event.target.checked)}/><span>Optional: allow selected source excerpts to be sent to Google Gemini for extra explanations and questions. I have permission to share this code.</span></label><p className="small-note">The walkthrough and five-question check work without Gemini. Backend and AI/ML role paths are not available yet.</p></div>}
    {screen === 'tour' && project && <div className="learning"><button className="back" onClick={() => setScreen('role')}><ArrowLeft size={16}/> Your project</button><div className="learning-head"><div><span className="eyebrow">YOUR CODE, IN FOUR STOPS</span><h1>{steps[stop].title}</h1><p>{project.name} · Stop {stop + 1} of 4</p></div><span className="counter">{String(stop + 1).padStart(2, '0')} / 04</span></div><div className="step-meter" aria-label={`${stop + 1} of 4 stops`}><i style={{ width: `${(stop + 1) * 25}%` }}/></div><article className="lesson"><span className="eyebrow">WHAT THE FILES SHOW</span><p className="explain">{steps[stop].explanation}</p><div className="proof">{steps[stop].trace.map((item, index) => <div className="proof-item" key={`${stop}-${index}`}><b>{item.point}</b><Evidence citation={item.citation} project={project}/></div>)}</div><div className="your-words"><span>TRY IT IN YOUR OWN WORDS</span><p>“{steps[stop].sayIt}”</p></div><details className="limits"><summary>What this does not prove</summary><p>{steps[stop].limitation}</p></details>{consent && <div className="deep"><button className="text-button" disabled={deepBusy} onClick={() => void loadDeep()}>{deepBusy ? 'Asking Gemini…' : deep[stop] ? 'Refresh extra explanation' : 'Go deeper with Gemini'} <ArrowRight size={15}/></button>{deepError && <p className="small-note" role="status">{deepError}</p>}{deep[stop] && <div className="deep-body"><p>{deep[stop].explanation}</p>{deep[stop].trace.map((item, index) => <div key={index}><b>{item.point}</b><Evidence citation={item.citation} project={project}/></div>)}</div>}</div>}</article><div className="tour-actions"><button className="secondary" disabled={stop === 0} onClick={() => { setStop(stop - 1); setDeepError('') }}><ArrowLeft size={16}/> Previous</button><button className="primary" onClick={() => { if (stop === 3) startQuick(); else { setStop(stop + 1); setDeepError('') } }}>{stop === 3 ? 'Try five questions' : 'Got it, keep going'} <ArrowRight size={16}/></button></div><p className="small-note">Read the cited lines before using these words in an interview. A scan can miss context.</p></div>}
    {screen === 'check' && project && <div className="learning"><button className="back" onClick={() => setScreen('tour')}><ArrowLeft size={16}/> Back to the walkthrough</button><span className="eyebrow">{advanced ? 'EXTRA PRACTICE' : 'FIVE-QUESTION CHECK'}</span><h1>Can you explain it?</h1><p className="lead">Take a guess. Each answer points to a file, so a miss becomes something you can learn.</p><div className="step-meter"><i style={{ width: `${quiz.length ? (questionIndex / quiz.length) * 100 : 0}%` }}/></div>{current && <section className="quiz"><span className="eyebrow">QUESTION {questionIndex + 1} OF {quiz.length}</span><h2>{current.prompt}</h2><div className="choices">{current.choices.map((option, index) => <button key={index} disabled={choice !== null} className={`${choice === index ? 'picked' : ''} ${choice !== null && index === current.correct ? 'right' : ''}`} onClick={() => setChoice(index)}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div>{choice !== null && <div className="feedback" role="status"><strong>{choice === current.correct ? 'That is it.' : 'Now you know where to look.'}</strong><p>{current.reason}</p><Evidence citation={current.citation} project={project}/></div>}<button className="primary" disabled={choice === null} onClick={submitAnswer}>{questionIndex + 1 === quiz.length ? 'See how I did' : 'Next question'} <ArrowRight size={16}/></button></section>}</div>}
    {screen === 'review' && project && <div className="learning review"><span className="eyebrow">YOUR PRACTICE RESULT</span><h1>{answers.filter(answer => answer.choice === answer.question.correct).length === answers.length && answers.length ? 'You can back it up.' : 'You know what to read next.'}</h1><p className="lead">This is practice with your project, not a certificate or proof that you authored the code.</p><div className="result-number"><strong>{answers.filter(answer => answer.choice === answer.question.correct).length}<span> / {answers.length}</span></strong><p>correct answers</p></div>{answers.filter(answer => answer.choice !== answer.question.correct).length > 0 && <div className="misses"><h2>Worth one more look</h2>{answers.filter(answer => answer.choice !== answer.question.correct).map((answer, index) => <div key={index}><b>{answer.question.prompt}</b><p>{answer.question.reason}</p><Evidence citation={answer.question.citation} project={project}/></div>)}</div>}<div className="review-actions"><button className="primary" onClick={() => { setStop(0); setScreen('tour') }}>Read my code again <ArrowRight size={16}/></button><button className="secondary" onClick={startQuick}><RotateCcw size={16}/> Retry five questions</button></div><div className="extra"><h2>Keep going with your project</h2><p>Explore all eight frontend areas at your pace. The file scan is immediate; optional Gemini explanations take longer.</p><button className="secondary" onClick={() => setScreen('library')}>Explore the full reading path <ArrowRight size={16}/></button></div>{consent && <div className="extra"><h2>Want a harder round?</h2><p>Gemini can draft up to ten source-backed questions per section. It takes longer and may be unavailable. The short check remains usable.</p><div className="extra-buttons">{['Tools & start','Screen & routes','State & data','Style','Build'].map((item, index) => <button key={item} disabled={advancedBusy} onClick={() => void loadAdvanced(index)}>{item}</button>)}</div>{advancedBusy && <p role="status">Preparing a section…</p>}{advancedError && <p role="status">{advancedError}</p>}</div>}</div>}
    {screen === 'library' && project && <div className="learning"><button className="back" onClick={() => setScreen('review')}><ArrowLeft size={16}/> Practice result</button><span className="eyebrow">THE FULL READING PATH</span><h1>Go where your curiosity leads.</h1><p className="lead">Eight areas to inspect in your own files. These are clues, not a claim that the scanner understood every line.</p><div className="chapter-tabs">{chapters.map((item, index) => <button key={item.title} className={index === chapter ? 'selected' : ''} onClick={() => { setChapter(index); setChapterError('') }}>{item.title}</button>)}</div><article className="lesson"><span className="eyebrow">{chapters[chapter].title.toUpperCase()}</span><h2>{chapters[chapter].goal}</h2><p className="explain">{chapters[chapter].finding}</p><div className="chapter-files"><strong>Files to inspect</strong>{chapters[chapter].files.length ? chapters[chapter].files.map(file => <Evidence key={file.path} citation={topicCitation(file, chapter)} project={project}/>) : <p>No clear match in this import. Do not invent one.</p>}</div>{consent && <div className="deep"><button className="text-button" disabled={chapterBusy} onClick={() => void loadChapter(chapter)}>{chapterBusy ? 'Asking Gemini…' : 'Ask Gemini to explain this area'} <ArrowRight size={15}/></button>{chapterError && <p className="small-note" role="status">{chapterError}</p>}{chapterLessons[chapter] && <div className="deep-body"><p>{chapterLessons[chapter].explanation}</p>{chapterLessons[chapter].trace.map((item, index) => <div key={index}><b>{item.point}</b><Evidence citation={item.citation} project={project}/></div>)}<p><b>Try saying:</b> {chapterLessons[chapter].sayIt}</p><p><b>Limit:</b> {chapterLessons[chapter].limitation}</p></div>}</div>}</article></div>}
  </main><footer>Recode 2026 · Built during ForgeHacks · Source-backed practice, not a skill certificate.</footer></div>
}
